apiVersion: appstudio.redhat.com/v1alpha1
kind: ImageRepository
metadata:
  annotations:
    image-controller.appstudio.redhat.com/update-component-image: "true"
  labels:
    appstudio.redhat.com/application: serverless-operator-136
    appstudio.redhat.com/component: kn-serving-test-servingcontainer-116
  name: kn-serving-test-servingcontainer-116
spec:
  image:
    name: serverless-operator-136/kn-serving-test-servingcontainer
    visibility: public
